<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="MAIN" Id="{319b139c-1377-4d52-94c4-4dd8285f8fc5}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
newVar : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[newVar := 1;
]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
      <LineId Id="8" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>